language: node_js
node_js:
  - "0.12"
  - "iojs"
before_install:
  # Setup sources and keys for LLVM
  - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main' >> /etc/apt/sources.list"
  - sudo sh -c "echo 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main' >> /etc/apt/sources.list"
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  # Setup packages and install LLVM
  - sudo apt-get update
  - sudo apt-get install -y --force-yes libstdc++6
  - sudo apt-get install -y llvm-3.5 llvm-3.5-dev llvm-3.5-runtime libllvm3.5 libllvm3.5-dbg
  # BDW GC built dependency
  - sudo apt-get install libc6-dev libgc-dev
before_script:
  # Add LLVM shared library
  - "export LD_LIBRARY_PATH=/usr/lib/llvm-3.5/lib:$LD_LIBRARY_PATH"
  - "export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
  # Setup library for development building
  - "node_modules/.bin/jake default ts:compile"
  - "npm run grammar"
  - "npm run gen-spec"
script:
  - "npm run test"
  - "npm run test-spec"
  - "npm run test-llvm"
after_script:
  - "npm run report-coverage"

