language: node_js
node_js:
  - "0.12"
  - "iojs"
before_script:
  - "node_modules/.bin/jake ts:compile"
  - "npm run grammar"
  - "npm run gen-spec"
script: "npm run test && npm run test-spec"
after_script:
  - "npm run report-coverage"

